### PR TITLE
Fix ProgramInfo.MapIDs for programs without maps on old kernels

### LINKED ISSUE #535: `ProgramInfo`'s `MapIDs()` bool returns false negatives
**Describe the bug**
Currently, the `(*ProgramInfo).MapIDs()`'s bool return value is simply determined by `pi.ids != nil`, `pi.ids` being allocated when `NrMapIds > 0`. The `NrMapIds` field will always be zero on older kernels that don't yet support it, so it's currently impossible to tell if the prog actually references 0 maps, or whether the kernel is too old to populate the field.

**Expected behavior**
On kernels that do support the NrMapIds field (4.15 and up), always return `true` for the second argument so the caller can determine for sure that the program has no map references.

This would require implementing a probe that inserts a prog that references a map and checking if NrMapIds is populated.

### PR DESCRIPTION
**Pull request by lmb**
Fixes #535.

### CODE REVIEW

File: info.go [hunk 1]
```diff
@@ -321,3 +327,30 @@ func EnableStats(which uint32) (io.Closer, error) {
...
+	}, SocketFilter, "MIT")
+	if err != nil {
+		return err
+	}
+	defer prog.Close()
+
+	err = sys.ObjInfo(prog, &sys.ProgInfo{
+		// NB: Don't need to allocate MapIds since the program isn't using
+		// any maps.
+		NrMapIds: 1,
```
Comment (ti-mo) [inline info.go:344]: Clever!

**Review by ti-mo — APPROVED** [review]
