### PR TITLE
test: Separate the netns for netkitanchor

### LINKED ISSUE #1577: Run netkit test in separate network namespace
This blew up on my machine today:
```
--- FAIL: TestNetkitAnchor (0.00s)
    quicktest.go:12:
        error:
          got non-nil value
        got:
          e"netlink receive: file exists"
        stack:
          /home/timo/github/cilium/ebpf/link/netkit_test.go:95
            qt.Assert(tb, qt.IsNil(err))
          /home/timo/github/cilium/ebpf/link/netkit_test.go:32
            linkA, ifIndex := mustAttachNetkit(t, a, ebpf.AttachNetkitPrimary)

FAIL
```

This test should be running in a new netns so it doesn't interfere with the host's network stack.

### PR DESCRIPTION
**Pull request by Jack-R-lantern**
Separated the network namespace for netkitanchor

close #1577

### CODE REVIEW

File: link/netkit_test.go [hunk 1]
```diff
@@ -4,12 +4,14 @@ package link
...
 import (
 	"fmt"
+	"runtime"
 	"sync/atomic"
 	"testing"
 
 	"github.com/go-quicktest/qt"
 	"github.com/jsimonetti/rtnetlink/v2"
 	"github.com/jsimonetti/rtnetlink/v2/driver"
+	"github.com/vishvananda/netns"
```
Comment (florianl) [inline link/netkit_test.go]: Instead of introducing a new dependency, I would prefer to follow the approach as in https://github.com/mdlayher/netlink/pull/110 - this would result in a bit more code, but I think it is worth it.

Comment (Jack-R-lantern) [reply link/netkit_test.go]: Could you share what additional benefits this approach provides beyond removing the dependency on the package?

My initial intention was to minimize the amount of utility code needed for testing, so I opted to use a new package.
Based on your feedback, I’ve reconsidered this, and I agree that if we plan to isolate network namespaces for all tests in the future, having our own utility functions could offer significant long-term advantages.

File: link/netkit_test.go [hunk 2]
```diff
@@ -31,6 +33,26 @@ func TestNetkitAnchor(t *testing.T) {
 	a := mustLoadProgram(t, ebpf.SchedCLS, ebpf.AttachNetkitPrimary, "")
 	b := mustLoadProgram(t, ebpf.SchedCLS, ebpf.AttachNetkitPrimary, "")
 
+	runtime.LockOSThread()
```
Comment (ti-mo) [inline link/netkit_test.go]: This is an awful amount of boilerplate for a test, and quite fragile. Flo gave you a good suggestion, but the mdl/netlink netns code is also 7 years old by this point. 🙂

Please copy a minimal subset of the approach I added in https://github.com/cilium/cilium/blob/5bb0c048cf8a00b110f283f110bd432cfb88b0f4/pkg/netns/netns_linux.go#L154 and https://github.com/cilium/cilium/blob/5bb0c048cf8a00b110f283f110bd432cfb88b0f4/pkg/testutils/netns/netns.go. The only exposed API surface should be `testutils.NetNS` (`NetNS.Do()`) and `testutils.NewNetNS`.

Comment (Jack-R-lantern) [reply link/netkit_test.go]: Thank you for the review.
I gained a lot of insight from how Cilium manages network namespaces.

File: btf/testdata/btf_testmod.btf
Comment (florianl) [inline btf/testdata/btf_testmod.btf:1]: Is this changed file some left over from some other change?

File: link/netkit_test.go [hunk 3]
```diff
@@ -1,4 +1,4 @@
-//go:build !windows
+//go:build linux
```
Comment (florianl) [inline link/netkit_test.go]: For consistency with other files, it should stay as `!windows`:
```suggestion
//go:build !windows
```

File: btf/testdata/vmlinux.btf.gz
Comment (florianl) [inline btf/testdata/vmlinux.btf.gz:1]: Similar to the comment on `btf/testdata/btf_testmod.btf`. Can this change be reverted?

File: btf/testdata/btf_testmod.btf
Comment (Jack-R-lantern) [reply btf/testdata/btf_testmod.btf:1]: The CI step “Generate and format code” failed.

According to the logs, the suggested action is to run make.
When I run make, it modifies btf_testmod.btf and vmlinux.btf.gz.

Is there a way to get the CI to pass without changing those two files?

For now, I’ll revert the changes to those two files temporarily.

File: link/netkit_test.go (hunk 3 above)
Comment (Jack-R-lantern) [reply link/netkit_test.go]: `netns` are supported only on Linux, so build errors occurred during cross build (e.g. darwin). I’ve made changes.

If to keep the current `go build directives`, I think we would need to leave stub implementations for operating systems other than Linux.

Do you have any recommended approach?

File: internal/testutils/netns.go [hunk 4]
```diff
@@ -0,0 +1,204 @@
...
+	return os.OpenFile(path, unix.O_RDONLY|unix.O_CLOEXEC, 0)
+}
+
+// getFromThread gets a file descriptor to the network namespace of a given pid
+// and tid.
+func getFromThread(pid, tid int) (*os.File, error) {
+	return getFromPath(fmt.Sprintf("/proc/%d/task/%d/ns/net", pid, tid))
+}
+
+func WithNetNameSpace(ns *NetNS, fn func(t *testing.T)) func(t *testing.T) {
```
Comment (ti-mo) [inline internal/testutils/netns.go]: This looks unused.

File: link/netkit_test.go (hunk 3 above)
Comment (ti-mo) [reply link/netkit_test.go]: Please stay consistent with the existing approach and conventions. Stubs are fine. 🙂

File: link/netkit_test.go [hunk 5]
```diff
@@ -31,7 +31,14 @@ func TestNetkitAnchor(t *testing.T) {
 	a := mustLoadProgram(t, ebpf.SchedCLS, ebpf.AttachNetkitPrimary, "")
 	b := mustLoadProgram(t, ebpf.SchedCLS, ebpf.AttachNetkitPrimary, "")
 
-	linkA, ifIndex := mustAttachNetkit(t, a, ebpf.AttachNetkitPrimary)
+	ns := testutils.NewNetNS(t)
+
+	var linkA Link
+	var ifIndex int
+	ns.Do(func() error {
+		linkA, ifIndex = mustAttachNetkit(t, a, ebpf.AttachNetkitPrimary)
```
Comment (ti-mo) [inline link/netkit_test.go]: IIRC calling t.Fatal in a goroutine other than the one the test is running in will cause a panic. `mustAttachNetkit` should take a NetNS and call only `rtnetlink.Dial()` and `AttachNetkit` in the new netns. Asserts should all be done outside of ns.Do().

File: internal/testutils/netns_linux.go [hunk 6]
```diff
@@ -0,0 +1,204 @@
+//go:build linux
+
```
Comment (ti-mo) [inline internal/testutils/netns_linux.go:2]:
```suggestion
// The netns implementation in this file was taken from cilium/cilium.
```

**Review by florianl — DISMISSED** [review]

File: internal/testutils/netns_other.go [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+type NetNS struct {
+}
+
+func NewNetNS(tb testing.TB) *NetNS {
+	tb.Helper()
+	return &NetNS{}
+}
+
+func (h *NetNS) Do(f func() error) error {
+	return f()
```
Comment (ti-mo) [inline internal/testutils/netns_other.go]: This shouldn't silently execute the function anyway, this does _not_ do what's expected. I'd return `ErrNotSupportedOnOS` here.

File: internal/testutils/netns_other.go [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+package testutils
+
+import "testing"
+
+type NetNS struct {
+}
+
+func NewNetNS(tb testing.TB) *NetNS {
+	tb.Helper()
+	return &NetNS{}
```
Comment (ti-mo) [inline internal/testutils/netns_other.go]: The function body should be:
```suggestion
	return nil
```

File: link/netkit_test.go [hunk 9]
```diff
@@ -50,14 +56,18 @@ func TestNetkitAnchor(t *testing.T) {
...
-				Interface: ifIndex,
-				Anchor:    anchor,
+			ns.Do(func() error {
+				linkB, err := AttachNetkit(NetkitOptions{
+					Program:   b,
+					Attach:    ebpf.AttachNetkitPrimary,
+					Interface: ifIndex,
+					Anchor:    anchor,
+				})
+				qt.Assert(t, qt.IsNil(err))
```
Comment (ti-mo) [inline link/netkit_test.go]: Same as https://github.com/cilium/ebpf/pull/1913#discussion_r2665251916, this can call `t.Fatal()` on a testing.T bound to another (parent) goroutine, which will panic. Declare `linkB` and `err` outside of ns.Do() and lift the asserts out of it as well.

File: link/netkit_test.go [hunk 10]
```diff
@@ -67,9 +77,13 @@ var prevIfindex atomic.Uint32
 
 func init() { prevIfindex.Store(1000 - 1) }
 
-func mustAttachNetkit(tb testing.TB, prog *ebpf.Program, attachType ebpf.AttachType) (Link, int) {
+func mustAttachNetkit(tb testing.TB, prog *ebpf.Program, attachType ebpf.AttachType, ns *testutils.NetNS) (Link, int) {
 	var err error
-	conn, err := rtnetlink.Dial(nil)
+	var conn *rtnetlink.Conn
+	err = ns.Do(func() error {
+		conn, err = rtnetlink.Dial(nil)
```
Comment (ti-mo) [inline link/netkit_test.go:80]: This first assigns directly from the closure to `err` in the outer scope, then assigns it again using the `err` returned from `ns.Do`. That's not ideal.

I'd do this:
```go
	qt.Assert(tb, qt.IsNil(ns.Do(func() (err error) {
		conn, err = rtnetlink.Dial(nil)
		return err
	})
```

And no `var err error` declaration in the outer scope.

File: link/netkit_test.go [hunk 11]
```diff
@@ -99,10 +113,14 @@ func mustAttachNetkit(tb testing.TB, prog *ebpf.Program, attachType ebpf.AttachT
 		qt.Assert(tb, qt.IsNil(conn.Link.Delete(uint32(ifIndex))))
 	})
 
-	link, err := AttachNetkit(NetkitOptions{
-		Program:   prog,
-		Attach:    attachType,
-		Interface: int(ifIndex),
+	var link Link
+	err = ns.Do(func() error {
```
Comment (ti-mo) [inline link/netkit_test.go]: Same as above.

File: internal/testutils/netns_other.go (hunk 8 above)
Comment (Jack-R-lantern) [reply internal/testutils/netns_other.go]: If return `nil`, then every test that creates a namespace via NewNetNS will need to add additional checks to handle the case where ns is nil.

I think this increases boilerplate.
Even so, do you think changing it to return nil is the right approach?

Comment (ti-mo) [reply internal/testutils/netns_other.go]: > If return `nil`, then every test that creates a namespace via NewNetNS will need to add additional checks to handle the case where ns is nil.

Not the case for two reasons:
- The test should be skipped on unsupported platforms, so the code wouldn't execute anyway
- Methods can be called on typed nil pointers as long as the receiver isn't accessed in said method

(see https://go.dev/play/p/nno5uE7FNWI for example)

Comment (Jack-R-lantern) [reply internal/testutils/netns_other.go]: Oh, I didn’t realize it worked that way. I’ll change it to return `nil`.

**Comment by Jack-R-lantern** [comment]
I’m not sure why the tag value in TestProgramInfo differs from the expected value.
Is there something additional that I need to do?

**Comment by ti-mo** [comment]
@Jack-R-lantern That's due to ongoing https://github.com/cilium/ebpf/pull/1932 and https://github.com/cilium/ebpf/pull/1933. We'll try to get those merged over the next few days. I've pushed a fixup and will merge this to get it over with. Thanks for bearing with me!

**Comment by Jack-R-lantern** [comment]
@ti-mo 

No problem at all.
I learned a lot from your kind review.
Thanks again!
