### PR TITLE
program: better error when loading a single program

### LINKED ISSUE #210: bad file descriptor: fd -1 is not pointing to valid bpf_map
I am getting this error when calling `ebpf.NewProgramWithOptions`. What is interesting is that the problem only observed when ebpf' s .c code carries these two definitions, once I comment these out the function succeeds.
```
static volatile const uint32_t svc_proto = 0;
static volatile const uint32_t svc_port = 0;
```

Here is ebpf c code:
```
#include "common.h"

#include <linux/if_ether.h>
#include <linux/swab.h>
#include <linux/pkt_cls.h>
#include <bpf/bpf_helpers.h>
#include <arpa/inet.h>

static volatile const uint32_t svc_proto = 0;
static volatile const uint32_t svc_port = 0;

static __always_inline int global_fn(uint32_t arg)
{
    return arg;
}

__section("classifier_egress_drop") int egress_drop(struct __sk_buff *skb)
{
    void *data_end = (void *)(unsigned long long)skb->data_end;
    void *data = (void *)(unsigned long long)skb->data;
    struct ethhdr *eth_h = data;

    /* Drop mailformated packet	*/
    if (data + sizeof(struct ethhdr) > data_end)
        return TC_ACT_SHOT;

    // Interested only in IPv6 packet
    if (ntohs(eth_h->h_proto) != ETH_P_IPV6)
    {
        return TC_ACT_OK;
    }
    // Now it is safe to type cast to ipv6 header struct
    // struct ip6_hdr *ipv6_h = (struct ip6_hdr *)(data - sizeof(struct ethhdr));
    // struct tcphdr *th = tcp_hdr(skb)

    global_fn(svc_proto);
    global_fn(svc_port);

    return TC_ACT_OK;
}

struct bpf_map_def __section("maps") map1 = {
    .type = BPF_MAP_TYPE_ARRAY,
    .key_size = sizeof(unsigned int),
    .value_size = 4096,
    .max_entries = 1,
};
```

Portion of go code:
```
func main() {

	ctx, cancel := context.WithTimeout(context.Background(), 600*time.Second)
	defer cancel()

	// Load eBPF from an elf file
	coll, err := ebpf.LoadCollectionSpec("ebpf/drop")
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not load collection from file: %v\n", err)
		return
	}
	 if _, ok := coll.Maps[".rodata"]; !ok {
	 	fmt.Fprintf(os.Stderr, "could not find .rodata section to set argument\n")
	 	return
	 }
	 if err := coll.RewriteConstants(map[string]interface{}{
	 	"svc_proto": uint32(6),
	 }); err != nil {
	 	fmt.Fprintf(os.Stderr, "could not find override arg with error: %+v\n", err)
	 	return
	 }
	 if err := coll.RewriteConstants(map[string]interface{}{
	 	"svc_port": uint32(2020),
	 }); err != nil {
	 	fmt.Fprintf(os.Stderr, "could not find override arg with error: %+v\n", err)
	 	return
	 }

	if _, ok := coll.Maps["map1"]; !ok {
		fmt.Fprintf(os.Stderr, "could not find map %q in loaded collection\n", "map1")
		return
	}
	_, err = ebpf.NewMap(coll.Maps["map1"])
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not make new map: %v\n", err)
		return
	}
	// Load the eBPF program egress_drop
	p, ok := coll.Programs["egress_drop"]
	if !ok {
		fmt.Fprintf(os.Stderr, "ebpf/drop does not container egress_drop section\n")
		return
	}
	fmt.Printf("Program: %+v\n", *p)
	egressDrop, err := ebpf.NewProgramWithOptions(p,
		ebpf.ProgramOptions{
			LogLevel: 1,
			LogSize:  65536,
		})
	if err != nil {
		fmt.Fprintf(os.Stderr, "NewProgramWithOptions could not load program %+v\n with error: %+v\n", *p, err)
		return
	}
	defer egressDrop.Close()
}
```

It is possible that I am doing something incorrectly, nevertheless declaration of two constant should not brea things or at least the error should be more helpful.

### PR DESCRIPTION
**Pull request by lmb**
Sometimes a user assumes that a ProgramSpec from a CollectionSpec can
be loaded with NewProgram instead of using NewCollection. This isn't
true unfortunately, and leads to a hard to understand error issued
by the verifier:

    bad file descriptor: fd -1 is not pointing to valid bpf_map

We can catch an unresolved map reference when loading a program and
use that to give a better error message to callers of NewProgram.

Fixes #210

### CODE REVIEW

File: prog.go [hunk 1]
```diff
@@ -20,6 +20,8 @@ import (
 // ErrNotSupported is returned whenever the kernel doesn't support a feature.
 var ErrNotSupported = internal.ErrNotSupported
 
+var errUnsatisfiedReference = errors.New("unsatisfied reference")
```
Comment (ti-mo) [inline prog.go:23]: The error string is nice and short, but still somewhat opaque. How about `unsatisfied reference to map`? It's currently only used for maps, so could be `errUnsatisfiedMapReference`.

File: prog.go [hunk 2]
```diff
@@ -135,7 +137,11 @@ func NewProgramWithOptions(spec *ProgramSpec, opts ProgramOptions) (*Program, er
 	handles := newHandleCache()
 	defer handles.close()
 
-	return newProgramWithOptions(spec, opts, handles)
+	prog, err := newProgramWithOptions(spec, opts, handles)
+	if errors.Is(err, errUnsatisfiedReference) {
+		return nil, fmt.Errorf("possible attempt to load program instead of collection: %w", err)
```
Comment (ti-mo) [inline prog.go:142]: This will come out as `possible attempt to load program instead of collection: unsatisfied reference`. I think we could drop the word 'possible' here: `cannot load program without loading its whole collection: unsatisfied reference to map`.

On the off chance the caller tries to load a bare prog with a missing map ref (no collection), there's still the 'unsatisfied reference to map' to help out as the more-specific error.

File: asm/load_store.go [hunk 3]
```diff
@@ -111,7 +113,7 @@ func LoadMapPtr(dst Register, fd int) Instruction {
 		OpCode:   LoadImmOp(DWord),
 		Dst:      dst,
 		Src:      PseudoMapFD,
-		Constant: int64(fd),
+		Constant: int64(uint32(fd) & math.MaxUint32),
```
Comment (ti-mo) [inline asm/load_store.go:116]: Just for my reference: is the mask required here? Won't the u32 conversion take care of truncating already?

File: testdata/loader-eb.elf [hunk 4]
```diff
@@ -0,0 +1 @@
+loader-clang-12-eb.elf
```
Comment (ti-mo) [inline testdata/loader-eb.elf:1]: Do we want to commit these to the repo?

**Review by ti-mo — COMMENTED** [review]
Looks good! Sorry for the delay. Minor nit on the error string and left a few questions.

File: prog.go (hunk 1 above)
Comment (lmb) [reply prog.go:23]: The error is actually `possible attempt to load program instead of collection: map foobar: unsatisfied reference`, so I'd leave it as it is.

File: prog.go (hunk 2 above)
Comment (lmb) [reply prog.go:142]: sgtm.

File: asm/load_store.go (hunk 3 above)
Comment (lmb) [reply asm/load_store.go:116]: You're right, it's not necessary.

File: testdata/loader-eb.elf (hunk 4 above)
Comment (lmb) [reply testdata/loader-eb.elf:1]: I think it's useful to have a symlink to whatever the version compiled with the latest clang is. The other option is to hardcode `loader-clang-12-eb.elf` in the tests and change them when we upgrade clang version.

Comment (lmb) [reply testdata/loader-eb.elf:1]: I don't mind either way, up to you.

File: prog.go (hunk 1 above)
Comment (ti-mo) [reply prog.go:23]: Okay, cool! That's perfect :+1:

File: testdata/loader-eb.elf (hunk 4 above)
Comment (ti-mo) [reply testdata/loader-eb.elf:1]: Nope, I prefer the symlink approach. :+1:

**Review by ti-mo — APPROVED** [review]
:rocket:
